version: "3.8"

services:
  basics-store-backend:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=basics
      - POSTGRESQL_PASSWORD=basics
      - POSTGRESQL_DATABASE=postgresql